### PR TITLE
Update custom service icon host and protocol and fix smtp mailer

### PR DESCRIPTION
**Pull request by xthursdayx**
Removed the `APP_URL` variable in favour of `EXTERNAL_DOMAIN` and specified that `https://` should be in included in this variable. This is meant to fix problems users were having with custom service icons and problems with the `Forgot Password` mail process. 

Related to https://github.com/getferdi/server/issues/79

### CODE REVIEW

**Comment by Ryonez** [comment]
I think `APP_URL` is the better variable to use the name of as it's an agnostic term. `EXTERNAL_DOMAIN` implies that the service is being made externally accessible, and that a domain is being used.

**Comment by xthursdayx** [comment]
> I think `APP_URL` is the better variable to use the name of as it's an agnostic term. `EXTERNAL_DOMAIN` implies that the service is being made externally accessible, and that a domain is being used.

`EXTERNAL_DOMAIN` was chosen because the server is designed to be accessible via `https` externally, via a reverse proxy. Using a reverse proxy necessitates the use of a domain name, obviously. Without using a domain name, Ferdi-server will only be accessible on your local network at `http://<local-server-ip>:3333` and password reset requests will not work.

**Comment by Ryonez** [comment]
I think that's making an assumption that a proxy would be in use and that it's available externally.

`https://` is also not part of a domain name, even if this is only used for external access `APP_URL` is better suited as that's what's actually being given, a url.

Why would the password resets break when an ip is being used? That sounds like an alarming bug.

**Comment by xthursdayx** [comment]
> I think that's making an assumption that a proxy would be in use and that it's available externally.
> 
To my mind, the point of running a Ferdi-server is to make it available externally, in lieu of using the default GetFerdi server. Because of this, I think it's safe to assume that users will be accessing Ferdi-server externally, via a reverse proxy. This is also what the README.md instructions suggest. 

> `https://` is also not part of a domain name, even if this is only used for external access `APP_URL` is better suited as that's what's actually being given, a url.
>
It seems that this concern is largely related to the semantics of term `domain` vs `url`. The choice is of no consequence to me; a variable is just a variable. I'm happy to use `APP_URL` if others prefer this. The documentation updated as part of this PR specifies that `https://` should be used, for example, if your server lives at `https://ferdiserver.tld`. The user can also use `http://` rather than `https://` if they chose to set up their reverse proxy with only `http` rather than `https`, for whatever reason. 

> Why would the password resets break when an ip is being used? That sounds like an alarming bug.
>
It isn't a bug. If you use a **local** IP for the password reset then the Ferdi-server will send an email with a password reset link that begins with your local IP address. This will obviously not work if you are not connected to your local network.

**Comment by Ryonez** [comment]
> To my mind, the point of running a Ferdi-server is to make it available externally, in lieu of using the default GetFerdi server. Because of this, I think it's safe to assume that users will be accessing Ferdi-server externally, via a reverse proxy. This is also what the README.md instructions suggest.

While it's not a terrible assumption, mine's done through a proxy itself, it's good try to account for the unexpected/unadvised use cases.

> It seems that this concern is largely related to the semantics of term `domain` vs `url`.

Yeah I'd agree that's my concern. The changes are good, I just think the terminology is off here.

> It isn't a bug. If you use a **local** IP for the password reset then the Ferdi-server will send an email with a password reset link that begins with your local IP address. This will obviously not work if you are not connected to your local network.

That makes more sense, the way it was said before made it sound like it just completely broke, rather than there being an issue if someone tried something outside of what they set it up for. If I was to make an assumption, it would be that if someone was to set this up locally with an ip, that they'd be making sure that ip is accessible to them to use it, when they use it.

**Comment by Ryonez** [comment]
Thank you. I know I was the only one talking about it, and I do appreciate you switching that.

**Comment by xthursdayx** [comment]
No worries. I updated both the variable and the documentation in both the main and docker README files. Hopefully this will clarify the intention of the `APP_URL` variable.

**Comment by xthursdayx** [comment]
If no one else has any concerns, I'll merge this, as I don't think it will impact anything else.

**Pull request merged**
